; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "TEXembed"
#define MyAppPublisher "SplitSecond Community"
#define MyAppExeName "texembed.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{5B7E8F2A-3C4D-4E5F-6A7B-8C9D0E1F2A3B}
AppName={#MyAppName}
AppVerName={#MyAppName}
AppPublisher={#MyAppPublisher}
DefaultDirName={commonpf}\TEXembed
DefaultGroupName={#MyAppName}
AllowNoIcons=yes
OutputBaseFilename=texembed-setup
Compression=lzma2/ultra64
SolidCompression=yes
LZMAUseSeparateProcess=yes
WizardStyle=modern dynamic
; Supported Windows versions: 7, 8, 8.1, 10, 11 (both 32 and 64 bit)
MinVersion=6.1sp1
SetupIconFile=icon.ico
ChangesAssociations=yes


[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "restartexplorer"; Description: "Restart Windows Explorer (Required to apply file icons)"; GroupDescription: "System Actions:"

[Files]
Source: "target\release\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "icon.ico"; DestDir: "{app}"; Flags: ignoreversion

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\icon.ico"
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\icon.ico"; Tasks: desktopicon

[Registry]
; Register .textures file extension
Root: HKCU; Subkey: "Software\Classes\.textures"; ValueType: string; ValueData: "splitsecond.texembed.textures"; Flags: uninsdeletevalue
Root: HKCU; Subkey: "Software\Classes\splitsecond.texembed.textures"; ValueType: string; ValueData: "TEXTURES File"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\splitsecond.texembed.textures\DefaultIcon"; ValueType: string; ValueData: "{app}\{#MyAppExeName},0"
Root: HKCU; Subkey: "Software\Classes\splitsecond.texembed.textures\shell\open\command"; ValueType: string; ValueData: """{app}\{#MyAppExeName}"" ""%1"""

; Register .streamtex file extension
Root: HKCU; Subkey: "Software\Classes\.streamtex"; ValueType: string; ValueData: "splitsecond.texembed.streamtex"; Flags: uninsdeletevalue
Root: HKCU; Subkey: "Software\Classes\splitsecond.texembed.streamtex"; ValueType: string; ValueData: "STREAMTEX File"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\splitsecond.texembed.streamtex\DefaultIcon"; ValueType: string; ValueData: "{app}\{#MyAppExeName},0"
Root: HKCU; Subkey: "Software\Classes\splitsecond.texembed.streamtex\shell\open\command"; ValueType: string; ValueData: """{app}\{#MyAppExeName}"" ""%1"""

[Run]
Filename: "{cmd}"; Parameters: "/c taskkill /f /im explorer.exe"; Flags: runhidden waituntilterminated; Tasks: restartexplorer
Filename: "{win}\explorer.exe"; Flags: runasoriginaluser nowait; Tasks: restartexplorer
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName,'&','&&')}}"; Flags: nowait postinstall skipifsilent

[Code]
const
  SHCNE_ASSOCCHANGED = $08000000;
  SHCNF_IDLIST = $0000;

procedure SHChangeNotify(wEventId: Longint; uFlags: Longint; dwItem1, dwItem2: Longint);
  external 'SHChangeNotify@shell32.dll stdcall';

procedure CurPageChanged(CurPageID: Integer);
var
  I: Integer;
begin
  if CurPageID = wpSelectTasks then
  begin
    for I := 0 to WizardForm.TasksList.Items.Count - 1 do
    begin
      if Pos('Restart Windows Explorer', WizardForm.TasksList.Items[I]) > 0 then
      begin
        WizardForm.TasksList.Checked[I] := True;
        WizardForm.TasksList.ItemEnabled[I] := False;
      end;
    end;
  end;
end;

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
begin
  if CurUninstallStep = usPostUninstall then
  begin
    { Notify Explorer to refresh file associations/icons.
      This does NOT kill or restart explorer.exe, so it works safely
      regardless of the uninstaller's elevation level or user session,
      and ShellExecAsOriginalUser/killing explorer is not usable here anyway
      (that function is only allowed during Setup, not Uninstall). }
    SHChangeNotify(SHCNE_ASSOCCHANGED, SHCNF_IDLIST, 0, 0);
  end;
end;
