; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "TEXembed"
#define MyAppPublisher "SplitSecond Community"
#define MyAppExeName "texembed.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{5B7E8F2A-3C4D-4E5F-6A7B-8C9D0E1F2A3B}
AppName={#MyAppName}
AppVerName={#MyAppName}
AppPublisher={#MyAppPublisher}
DefaultDirName={commonpf}\TEXembed
DefaultGroupName={#MyAppName}
AllowNoIcons=yes
OutputBaseFilename=TEXembed_win-x64
Compression=lzma2/ultra64
LZMANumFastBytes=273
SolidCompression=yes
LZMAUseSeparateProcess=yes
WizardStyle=modern dynamic
; Supported Windows versions: 10 and 11 (64-bit only)
MinVersion=10.0
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
UninstallDisplayIcon={app}\{#MyAppExeName}
SetupIconFile=icon.ico
ChangesAssociations=yes


[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "target\release\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "icon.ico"; DestDir: "{app}"; Flags: ignoreversion

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\icon.ico"
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\icon.ico"; Tasks: desktopicon

[Registry]
; Remove leftover per-user registrations from older (32-bit) versions.
; HKCU\Software\Classes overrides HKLM\Software\Classes, so stale entries
; there would keep pointing at the old "Program Files (x86)" path.
Root: HKCU; Subkey: "Software\Classes\.textures"; ValueType: none; Flags: deletekey dontcreatekey
Root: HKCU; Subkey: "Software\Classes\.streamtex"; ValueType: none; Flags: deletekey dontcreatekey
Root: HKCU; Subkey: "Software\Classes\splitsecond.texembed.textures"; ValueType: none; Flags: deletekey dontcreatekey
Root: HKCU; Subkey: "Software\Classes\splitsecond.texembed.streamtex"; ValueType: none; Flags: deletekey dontcreatekey

; Register .textures file extension (machine-wide, since Setup runs elevated)
Root: HKLM; Subkey: "Software\Classes\.textures"; ValueType: string; ValueData: "splitsecond.texembed.textures"; Flags: uninsdeletevalue
Root: HKLM; Subkey: "Software\Classes\splitsecond.texembed.textures"; ValueType: string; ValueData: "TEXTURES File"; Flags: uninsdeletekey
Root: HKLM; Subkey: "Software\Classes\splitsecond.texembed.textures\DefaultIcon"; ValueType: string; ValueData: "{app}\icon.ico"
Root: HKLM; Subkey: "Software\Classes\splitsecond.texembed.textures\shell\open\command"; ValueType: string; ValueData: """{app}\{#MyAppExeName}"" ""%1"""

; Register .streamtex file extension (machine-wide, since Setup runs elevated)
Root: HKLM; Subkey: "Software\Classes\.streamtex"; ValueType: string; ValueData: "splitsecond.texembed.streamtex"; Flags: uninsdeletevalue
Root: HKLM; Subkey: "Software\Classes\splitsecond.texembed.streamtex"; ValueType: string; ValueData: "STREAMTEX File"; Flags: uninsdeletekey
Root: HKLM; Subkey: "Software\Classes\splitsecond.texembed.streamtex\DefaultIcon"; ValueType: string; ValueData: "{app}\icon.ico"
Root: HKLM; Subkey: "Software\Classes\splitsecond.texembed.streamtex\shell\open\command"; ValueType: string; ValueData: """{app}\{#MyAppExeName}"" ""%1"""

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName,'&','&&')}}"; Flags: nowait postinstall skipifsilent

[Code]
const
  SHCNE_ASSOCCHANGED = $08000000;
  SHCNF_IDLIST = $0000;

procedure SHChangeNotify(wEventId: Longint; uFlags: Longint; dwItem1, dwItem2: Longint);
  external 'SHChangeNotify@shell32.dll stdcall';

procedure CurStepChanged(CurStep: TSetupStep);
begin
  if CurStep = ssPostInstall then
  begin
    { Notify Explorer to refresh file associations/icons without killing
      or restarting explorer.exe. }
    SHChangeNotify(SHCNE_ASSOCCHANGED, SHCNF_IDLIST, 0, 0);
  end;
end;

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
begin
  if CurUninstallStep = usPostUninstall then
  begin
    { Notify Explorer to refresh file associations/icons.
      This does NOT kill or restart explorer.exe, so it works safely
      regardless of the uninstaller's elevation level or user session,
      and ShellExecAsOriginalUser/killing explorer is not usable here anyway
      (that function is only allowed during Setup, not Uninstall). }
    SHChangeNotify(SHCNE_ASSOCCHANGED, SHCNF_IDLIST, 0, 0);
  end;
end;
